services:
- type: web
  name: trackflow-frontend
  env: static
  buildCommand: npm install && npm run build
  staticPublishPath: build
  buildFilter:
    paths:
    - frontend/**/*
  repo: https://github.com/your-username/trackflow
  rootDir: frontend
