#!/usr/bin/env python3
"""
Export all artists from the database to CSV, excluding specific artist names.
"""

import csv
import sys
import os
from datetime import datetime

# Add the parent directory to the path so we can import from the backend
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from database import SessionLocal
from models import Artist

# List of artist names to exclude
EXCLUDED_ARTISTS = {
    "The Lemonheads",
    "Death Cab for Cutie",
    "Iggy Pop",
    "Johnny Cash",
    "ABBA",
    "Mac DeMarco",
    "Marmalade",
    "Violent Femmes",
    "The Millennium",
    "Uncle Tupelo",
    "...And You Will Know Us by the Trail of Dead",
    "Angel Olsen",
    "Leonard Cohen",
    "Willie Nelson",
    "Viagra Boys",
    "Dismemberment Plan",
    "The Easybeats",
    "Queens of the Stone Age",
    "Beach Bunny",
    "DIIV",
    "Khruangbin",
    "Arcade Fire",
    "Led Zeppelin",
    "Black Box Recorder",
    "Origami Angel",
    "Bauhaus",
    "Cleaners from Venus",
    "Nicholas Britell",
    "Parquet Courts",
    "Richard Dawson",
    "The Smiths",
    "Portishead",
    "Purple Mountains",
    "Sharon Van Etten",
    "TV Sounds Unlimited",
    "The Boys Next Door",
    "Sunny Day Real Estate",
    "Richard Hawley",
    "The Byrds",
    "Teenage Fanclub",
    "Jim Croce",
    "Motorama",
    "Gregory Alan Isakov",
    "Fats Domino",
    "Robbie Williams",
    "Yusuf / Cat Stevens",
    "The Mamas & The Papas",
    "Bill Withers",
    "The Clash",
    "Phoebe Bridgers",
    "Best Coast",
    "Buffalo Springfield",
    "The Sundays",
    "Stephen Malkmus",
    "The Waterboys",
    "The Only Ones",
    "Kiwi jr.",
    "The Beta Band",
    "Camera Obscura",
    "Andrew Bird",
    "The Jesus and Mary Chain",
    "Glen Campbell",
    "16 Horsepower",
    "The Mountain Goats",
    "Arthur Lee",
    "Buddy Holly",
    "The Walkmen",
    "Andy Shauf",
    "The Rolling Stones",
    "Blur",
    "PJ Harvey",
    "Nick Cave & The Bad Seeds",
    "Summer Salt",
    "The Handsome Family",
    "Bruce Springsteen",
    "The Exploding Hearts",
    "Tom Waits",
    "George Harrison",
    "Frank Turner",
    "The Interrupters",
    "Morrissey",
    "Olivia Newton-John",
    "Manic Street Preachers",
    "The Velvet Underground",
    "The Kinks",
    "Prince",
    "Van Morrison",
    "Pavement",
    "Depeche Mode",
    "The Modern Lovers",
    "Bill Fay",
    "Hank Williams",
    "Magazine",
    "Frankie Cosmos",
    "Crosby, Stills, Nash & Young",
    "IDLES",
    "Spoon",
    "Lou Reed",
    "The Jam",
    "Beach Fossils",
    "Deep Purple",
    "Wet Leg",
    "Fiona Apple",
    "St. Vincent",
    "Chuck Berry",
    "Frankie Valli",
    "Gorky's Zygotic Mynci",
    "Echo & the Bunnymen",
    "Commodores",
    "David Bowie",
    "Pulp",
    "Kate Bush",
    "The Cure",
    "The Dresden Dolls",
    "The Lemon Twigs",
    "Destroyer",
    "The Beatles",
    "Big Thief",
    "U2",
    "David Gilmour",
    "The Teardrop Explodes",
    "The Stone Roses",
    "Calexico",
    "Nick Lowe",
    "Suede",
    "Thunderclap Newman",
    "John Grant",
    "The Stills-Young Band",
    "Grinderman",
    "John Prine",
    "Protomartyr",
    "Kendrick Lamar",
    "Red House Painters",
    "Neil Young",
    "Elvis Costello & The Imposters",
    "Morphine",
    "Elvis Presley",
    "Soccer Mommy",
    "The Field Mice",
    "The Flying Burrito Brothers",
    "The Libertines",
    "The Maccabees",
    "Eric Clapton",
    "The Undertones",
    "Arctic Monkeys",
    "Reigning Sound",
    "Creedence Clearwater Revival",
    "Crosby, Stills & Nash",
    "The Yardbirds",
    "Syd Barrett",
    "Belle and Sebastian",
    "Fleetwood Mac",
    "Nick Drake",
    "Randy Newman",
    "Gram Parsons",
    "Todd Rundgren",
    "Wings",
    "Stephen Malkmus & The Jicks",
    "Super Furry Animals",
    "The Verve",
    "Mitski",
    "Bones Garage",
    "Cass McCombs",
    "Sparklehorse",
    "The Walker Brothers",
    "Lush",
    "Mild High Club",
    "Kanye West",
    "Lucy Dacus",
    "T. Rex",
    "Blondie",
    "John Lennon",
    "The Strokes",
    "Five",
    "Hamilton Leithauser",
    "Wilco",
    "Mark Lanegan",
    "Faye Webster",
    "Television",
    "Etta James",
    "Sufjan Stevens",
    "The Alan Parsons Project",
    "Sturgill Simpson",
    "The The",
    "Elvis Costello & The Attractions",
    "The Drifters",
    "The Avett Brothers",
    "Joni Mitchell",
    "Unknown Mortal Orchestra",
    "Elvis Costello",
    "Lorde",
    "Lloyd Cole and the Commotions",
    "The Beach Boys",
    "The Zombies",
    "Grandaddy",
    "The Pastels",
    "The Breeders",
    "Dusty Springfield",
    "Chubby Checker",
    "Silver Jews",
    "The Beths",
    "Derek & The Dominos",
    "The Chills",
    "The Magnetic Fields",
    "Paul McCartney",
    "Talking Heads",
    "Frank Sinatra",
    "Pixies",
    "The Carpenters",
    "Another Sunny Day",
    "Jeff Beck",
    "The Veils",
    "Courtney Barnett",
    "Ray Charles",
    "Inspiral Carpets",
    "Rolling Blackouts Coastal Fever",
    "Elbow",
    "Fred Neil",
    "The Gun Club",
    "Elliott Smith",
    "Songs: Ohia",
    "Screaming Females",
    "Stars",
    "Radiohead",
    "Loudon Wainwright III",
    "Wipers",
    "Waxahatchee",
    "Fastball",
    "Bee Gees",
    "Paul Simon",
    "The National",
    "The Chameleons",
    "Pool Kids",
    "Kris Kristofferson",
    "Joy Division",
    "Metronomy",
    "Simon & Garfunkel",
    "Cream",
    "Gilbert O'Sullivan",
    "The Gaslight Anthem",
    "The Last Shadow Puppets",
    "Richard & Linda Thompson",
    "Chris Bell",
    "Pink Floyd",
    "Big Star",
    "Fontaines D.C.",
    "X",
    "The Replacements",
    "Camel",
    "Grateful Dead",
    "Massive Attack",
    "John Cale",
    "Father John Misty",
    "The Aquadolls",
    "R.E.M.",
    "Deerhunter",
    "Aztec Camera",
    "Fleet Foxes",
    "Alfa",
    "John Dowland",
    "Blvk",
    "Outkast",
    "Sir Chloe",
    "James Brown",
    "Young the Giant",
    "Mindless Self Indulgence",
    "L.A. Salami",
    "Primal Scream",
    "The Shadows",
    "The Monkees",
    "Mountain",
    "Wire",
    "Minutemen",
    "Sonic Youth",
    "Duster",
    "Shellac",
    "Liars",
    "Weezer",
    "Cat Power",
    "Clap Your Hands Say Yeah",
    "Omni",
    "Modern Baseball",
    "Basement",
    "Japandroids",
    "AJJ",
    "Mannequin Pussy",
    "No Vacation",
    "Ted Leo and the Pharmacists",
    "The Aquabats!",
    "Mclusky",
    "They Might Be Giants",
    "Bloc Party",
    "The Killers",
    "The Cribs",
    "Laura Stevenson",
    "Yuck",
    "PAW Patrol",
    "Vampire Weekend",
    "Chris Farren",
    "Jeff Rosenstock",
    "Team Sleep",
    "Islands",
    "Adventures",
    "Razorlight",
    "Darwin Deez",
    "Briston Maroney",
    "d4vd",
    "glaive",
    "Franz Ferdinand",
    "Eskimo Joe",
    "Placebo",
    "Klaxons",
    "Art vs Science",
    "The xx",
    "Dum Dum Girls",
    "Nothing But Thieves",
    "Deafheaven",
    "Foals",
    "White Lies",
    "The Zutons",
    "Kaiser Chiefs",
    "The Pigeon Detectives",
    "Adele",
    "Bobby Darin",
    "Albert King",
    "Timber Timbre",
    "Carneyval",
    "90 Day Men",
    "Robbie Fulks",
    "fIREHOSE",
    "Failure",
    "Gang Of Four",
    "Vundabar",
    "American Football",
    "Heatmiser",
    "Jeff Buckley",
    "Shudder To Think",
    "Joyce Manor",
    "Neutral Milk Hotel",
    "Panchiko",
    "NerdOut",
    "Polvo",
    "Bingo Players",
    "Lisa Hannigan",
    "Say Anything",
    "Sebadoh",
    "The Smile",
    "Brainbox",
    "Sorority Noise",
    "The Voidz",
    "Unwound",
    "Big Brother & The Holding Company",
    "Elastica",
    "Pile",
    "Sleater-Kinney",
    "Radiator Hospital",
    "Ought",
    "Everclear",
    "beabadoobee",
    "Alex G",
    "b√¥a",
    "Graeme Norgate",
    "Jets To Brazil",
    "Panic! At The Disco",
    "The Flaming Lips",
    "Polar Extremes",
    "King Princess",
    "The Front Bottoms",
    "Fugazi",
    "Bob Dylan",
    "CyHi",
    "Chet Baker",
    "Little Richard",
    "The Temptations",
    "Snail Mail",
    "Mazzy Star"
}

def export_artists_excluding_list():
    """Export all artists from the database to CSV, excluding the specified list."""
    
    db = SessionLocal()
    try:
        # Get all artists from the database
        artists = db.query(Artist).all()
        
        # Filter out excluded artists
        filtered_artists = [artist for artist in artists if artist.name not in EXCLUDED_ARTISTS]
        
        # Create CSV filename with timestamp
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"artists_export_{timestamp}.csv"
        
        print(f"Found {len(artists)} total artists in database")
        print(f"Excluding {len(EXCLUDED_ARTISTS)} artists from the list")
        print(f"Exporting {len(filtered_artists)} artists to {filename}")
        
        # Write to CSV with new IDs starting from 377
        with open(filename, 'w', newline='', encoding='utf-8') as csvfile:
            fieldnames = ['id', 'name', 'image_url', 'user_id']
            writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
            
            writer.writeheader()
            for i, artist in enumerate(filtered_artists):
                new_id = 377 + i  # Start from 377
                writer.writerow({
                    'id': new_id,
                    'name': artist.name,
                    'image_url': artist.image_url,
                    'user_id': artist.user_id
                })
        
        print(f"✅ Successfully exported {len(filtered_artists)} artists to {filename}")
        print(f"📝 New IDs assigned from 377 to {376 + len(filtered_artists)}")
        
        # Show some statistics
        print(f"\n📊 Statistics:")
        print(f"   Total artists in database: {len(artists)}")
        print(f"   Artists in exclusion list: {len(EXCLUDED_ARTISTS)}")
        print(f"   Artists exported: {len(filtered_artists)}")
        print(f"   Artists excluded: {len(artists) - len(filtered_artists)}")
        print(f"   ID range: 377 - {376 + len(filtered_artists)}")
        
        return filename
        
    except Exception as e:
        print(f"❌ Error exporting artists: {e}")
        return None
    finally:
        db.close()

if __name__ == "__main__":
    export_artists_excluding_list() 